version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache
      - restore_cache:
          keys:
            - root-cache-{{ checksum "yarn.lock" }}
            - root-cache
      - run:
          name: Bootstrap packages
          command: yarn bootstrap
      - save-cache:
          key: root-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save-cache:
          key: root-cache
          paths:
            - node_modules
      - save-cache:
          key: yarn-cache
          paths:
            - ~/.cache/yarn
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache
      - restore_cache:
          keys:
            - root-cache-{{ checksum "yarn.lock" }}
            - root-cache
      - run:
          name: Test packages
          command: yarn test
workflows:
  version: 2
  build-n-test:
      jobs:
        - build:
            filters:
              tags:
                only: /.*/
        - test:
            requires:
              - build
            filters:
              tags:
                only: /.*/

